api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "rental-deposit"
type = "function"
uid = "dd6f3f2f-83b7-9045-5023-f657bd99f49f97965b67"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
